
import { Translations } from './types';

export const CATEGORIES = [
  'Groceries', 'Utilities', 'Rent', 'Salary', 'Freelance', 'Entertainment', 'Transport', 'Healthcare', 'Other'
];

export const translations: Translations = {
  en: {
    appName: 'Expense Tracker',
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Log in to manage your finances.',
    username: 'Username',
    password: 'Password',
    login: 'Login',
    logout: 'Logout',
    dashboard: 'Dashboard',
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    netProfit: 'Net Profit',
    loss: 'Loss',
    monthly: 'Monthly',
    annually: 'Annually',
    expenseBreakdown: 'Expense Breakdown',
    recentTransactions: 'Recent Transactions',
    addTransaction: 'Add Transaction',
    editTransaction: 'Edit Transaction',
    description: 'Description',
    amount: 'Amount',
    date: 'Date',
    category: 'Category',
    type: 'Type',
    income: 'Income',
    expense: 'Expense',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    selectCategory: 'Select a category',
    getFinancialAdvice: 'Get AI Financial Advice',
    generatingAdvice: 'Generating your financial advice...',
    adviceFromAI: 'Advice from our AI',
    language: 'Language',
    english: 'English',
    arabic: 'Arabic',
    noTransactions: 'No transactions yet. Add one to get started!',
    noExpenseData: 'No expense data for this period.',
    confirmDelete: 'Are you sure you want to delete this transaction?',
  },
  ar: {
    appName: 'متتبع المصاريف',
    loginTitle: 'مرحبًا بعودتك',
    loginSubtitle: 'سجل الدخول لإدارة أموالك.',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    dashboard: 'لوحة التحكم',
    totalIncome: 'إجمالي الدخل',
    totalExpenses: 'إجمالي المصاريف',
    netProfit: 'صافي الربح',
    loss: 'خسارة',
    monthly: 'شهريًا',
    annually: 'سنويًا',
    expenseBreakdown: 'تفاصيل المصاريف',
    recentTransactions: 'المعاملات الأخيرة',
    addTransaction: 'إضافة معاملة',
    editTransaction: 'تعديل المعاملة',
    description: 'الوصف',
    amount: 'المبلغ',
    date: 'التاريخ',
    category: 'الفئة',
    type: 'النوع',
    income: 'دخل',
    expense: 'مصروف',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    selectCategory: 'اختر فئة',
    getFinancialAdvice: 'احصل على نصيحة مالية بالذكاء الاصطناعي',
    generatingAdvice: 'جاري إنشاء نصيحتك المالية...',
    adviceFromAI: 'نصيحة من الذكاء الاصطناعي لدينا',
    language: 'اللغة',
    english: 'الإنجليزية',
    arabic: 'العربية',
    noTransactions: 'لا توجد معاملات حتى الآن. أضف واحدة للبدء!',
    noExpenseData: 'لا توجد بيانات مصاريف لهذه الفترة.',
    confirmDelete: 'هل أنت متأكد أنك تريد حذف هذه المعاملة؟',
  }
};
